version: "3.7"

services:
  job-storage:
    image: redis:alpine
    ports:
      - 6379:6379
  job-storage-gui:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
volumes:
  redisinsight:
