@token = Bearer {{$dotenv FIREBASE_TOKEN}}

POST http://localhost:5000/api/video/transcode HTTP/1.1
Content-Type: application/json

{
    "path": "NEW GAME!\\NEW GAME!\\NEW GAME! #01「なんだかホントに入社した気分です!」.mp4"
}
###
GET http://localhost:5000/api/video/ HTTP/1.1
Authorization: {{token}}
###
GET http://localhost:5000/api/video/NEW%20GAME! HTTP/1.1
###
GET http://localhost:5000/stream/1234567/master.mpd HTTP/1.1
###
GET http://localhost:5000/hangfire HTTP/1.1
###
GET http://localhost:5000/ HTTP/1.1
