name: Worker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-
      - id: dotnet-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.net-version
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ steps.dotnet-version.outputs.content }}
      - uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: "5.x"
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
      - name: Build with dotnet
        run: |
          dotnet publish -c Release --self-contained -r win10-x64 -o out \
          -p:Version=${{ steps.gitversion.outputs.fullSemVer }} \
          -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
          -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
          -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }} \
          Worker
      - uses: actions/upload-artifact@v1
        with:
          name: worker_${{ steps.gitversion.outputs.fullSemVer }}
          path: out
