name: Worker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet publish -c Release --self-contained -r win10-x64 -o out Worker
    - uses: actions/upload-artifact@v1
      with:
        name: worker_${{ github.sha }}
        path: out
