name: Worker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          nuget-
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - run: git fetch --prune --unshallow
    - uses: gittools/actions/gitversion/setup@v0.9.5
      with:
          versionSpec: '5.3.x'
    - id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.5
    - name: Build with dotnet
      run: |
        dotnet publish -c Release --self-contained -r win10-x64 -o out \
        -p:Version=${{ steps.gitversion.outputs.fullSemVer }} \
        -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
        -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
        -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }} \
        Worker
    - uses: actions/upload-artifact@v1
      with:
        name: worker_${{ steps.gitversion.outputs.fullSemVer }}
        path: out
